import'package:flutter/material.dart';
final coinTypeList = [
  {
    'coinType':'btc',
    'icon':Image.asset('assets/icon/coinType/btc.png'),
  },
  {
    'coinType':'bsv',
    'icon':Image.asset('assets/icon/coinType/bsv.png'),
  },
  {
    'coinType':'bch',
    'icon':Image.asset('assets/icon/coinType/bch.png'),
  },
  {
    'coinType':'dcr',
    'icon':Image.asset('assets/icon/coinType/dcr.png'),
  },
  {
    'coinType':'zec',
    'icon':Image.asset('assets/icon/coinType/zec.png'),
  },
  {
    'coinType':'ltc',
    'icon':Image.asset('assets/icon/coinType/ltc.png'),
  },
  {
    'coinType':'eth',
    'icon':Image.asset('assets/icon/coinType/eth.png'),
  },
  {
    'coinType':'etp',
    'icon':Image.asset('assets/icon/coinType/etp.png'),
  },
];